### ISSUE TITLE
some methods questions & combining efforts?

### ISSUE THREAD

**Issue by PeerHerholz** [wmvanvliet/mne-rsa#7]
Hi @wmvanvliet,

I meant to contact you for a while regarding this cool project of your's. I'm not sure if the issue format
is the best to discuss my questions, but as it's completely open it's of course a favourable one. 

I would like to ask two methods related questions:

1) Are you thinking about supporting multivariate noise normalization during computation of the RDMs as outlined and implemented [here](https://github.com/mvdoc/meegnobis)  & [here](https://github.com/m-guggenmos/megmvpa)?
2) Is anything planned regarding significance testing (e.g. `permutation` and/or `bootstrap` tests)?

Something a little off, but over at [urial](https://github.com/PeerHerholz/URIAL) I played a bit around with RSA focusing fMRI, as I needed it for parts of my PhD. As you mentioned contributions regarding fMRI are welcome, I wondered if it might be worth talking about combining our efforts? 

It would be cool to hear your thoughts on any of the topics I mentioned. 

Cheers, Peer

**Comment by wmvanvliet** [comment]
Hi @PeerHerholz,

thank you for reaching out!

 1. Noise normalization is planned. It needs a little thought in the case where we make spatial searchlight patches, since multivariate normalization will move activity around spatially.
 2. No significance testing is planned, since [MNE-Python already provides it](https://mne.tools/stable/auto_tutorials/index.html#statistical-analysis-of-sensor-data) for all use cases that I have in mind for it.

I would greatly welcome a PR for functions to provide an interface between nifty files and the [`dsm_array`](https://users.aalto.fi/~vanvlm1/mne-rsa/functions/mne_rsa.dsm_array.html) function, mimicking the [`dsm_epochs`](https://users.aalto.fi/~vanvlm1/mne-rsa/functions/mne_rsa.dsm_epochs.html) function.

**Comment by wmvanvliet** [comment]
I've taken a stab at nifti intergration, see #10
